name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:20

    env:
      TRAVIS_PULL_REQUEST: ${{ github.event.pull_request.number }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Build
        run: |
          git clone https://github.com/frodrigo/gl-style-package-spec.git
          cd gl-style-package-spec
          bash ./task/run.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gl-style-package-spec/build